version: '{branch}-build-{build}'

shallow_clone: true

notifications:
  - provider: Webhook
    url: https://hooks.aethonan.pro/appveyor/388950989/

install:
  - cinst nsis --version 3.02
  - cinst pandoc --version 1.17.0.2
  - cd Perl\Scripts
  - .\install-gnu-utilities-collection.bat
  - .\install-strawberry-perl-package-for-fusioninventory-agent.bat
  - .\install-fusioninventory-agent.bat
  - .\patch-fusioninventory-agent.bat
  - .\update-ids-repositories.bat
  - cd ..\..

test: off

build_script:
  - cd NSIS
  - .\FusionInventory-Agent.bat
  - dir

artifacts:
  - path: NSIS/*.txt,Perl/Scripts/*build.log*
    name: logs
  - path: NSIS/*.exe
    name: exes
  - path: NSIS/*.md5,NSIS/*.sha1,NSIS/*.sha256
    name: chks

deploy:
  release: 'FIA Windows Installer $(APPVEYOR_REPO_TAG_NAME)'
  description: 'Teclib release candidate'
  provider: GitHub
  auth_token:
    secure: 2bHwACjD0EnWh8Y+X7Z49T9Yjp6tP9mAM+5cPXGSZ4VcSmptsZz0G0pgXjLVMTgp
  artifact: exes,chks
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
